import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Favicon from '../../public/airbnb.ico'
import AppThemeProvider from '@/Theme/AppThemeProvider'
import CssBaseline from '@mui/material/CssBaseline'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Nhà nghỉ dưỡng & Căn hộ cao cấp cho thuê - Airbnb',
    description: 'Generated by create next app',
    icons: [{ rel: 'icon', url: Favicon.src }],
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <AppThemeProvider>
                    <CssBaseline />
                    {children}
                </AppThemeProvider>
            </body>
        </html>
    )
}
